doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '13'
        charset: UTF8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    ApplicationToolsBundle: ~
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App