# config/packages/fos_user.yaml
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    #user_class:     Sonata\UserBundle\Entity\BaseUser
    user_class:     App\Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\Group

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address: "test@domain.com"
        sender_name: "test@domain.com"

#fos_user:
#    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
#    firewall_name: main
#    user_class: App\Entity\User
#    from_email:
#        address: "test@domain.com"
#        sender_name: "test@domain.com"