twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
        - ApplicationToolsBundle:Form:dependent_filtered_entity_widget.html.twig
        - ApplicationToolsBundle:Form:editable_combobox_widget.html.twig
        - ApplicationToolsBundle:Form:formfield_cloacker_widget.html.twig
        - ApplicationToolsBundle:Form:file_field_ext.html.twig