#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
    
app_default_verificacion:
    path: /verificacion
    defaults:
        _controller: App\Controller\DefaultController::verificacionAction
        
app_default_imprimirmasivo:
    path: /imprimirmasivo
    defaults:
        _controller: App\Controller\DefaultController::imprimirMasivoAction
        
app_default_generarcertificadosmasivo:
    path: /generarcertificadosmasivo
    defaults:
        _controller: App\Controller\DefaultController::generarCertificadosMasivoAction